version: 2.1
jobs:
  build:
    working_directory: ~/Movie-List-Sample
    docker:
      - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
